#!/usr/bin/env bash

# To adapt this script for your monitor:
#   1. Make sure you have i2c-tools and ddccontrol installed:
#          sudo apt-get install i2c-tools ddccontrol
#   2. Enable kernel module
#          sudo modprobe i2c-dev
#   3. Find out the id's of the monitors:
#          sudo i2cdetect -l
#      and try the id's of the form i2c-X:
#          sudo ddccontrol dev:/dev/i2c-X
#
#   4. If you have found the monitor, look for the address that
#      identifies brightness. Replace the 0x10 with this.

brightness=0

if [[ ! -z $1 ]]; then
	sign=${1:0:1}
fi

if [[ -z $1 ]] || [[ "$sign" = "+" ]] || [[ "$sign" = "-" ]]; then
	brightness=$(ddccontrol dev:/dev/i2c-6 -r 0x10 2>/dev/null | tail -1 | awk -F '[//]' '{ print $(NF-1) }')
	change=true
fi

if [[ -z $1 ]]; then
	echo "$brightness"
else
	if [[ "$change" = true ]]; then
		brightness=$(($brightness+$1))
		if [[ $brightness -gt 100 ]]; then
			brightness=100
		elif [[ $brightness -lt 0 ]]; then
			brightness=0
		fi
	else
		brightness="$1"
	fi
	
	if [[ 0 -le $brightness ]] && [[ $brightness -le 100 ]]; then
		ddccontrol dev:/dev/i2c-6 -r 0x10 -w $brightness > /dev/null 2>&1
		ddccontrol dev:/dev/i2c-7 -r 0x10 -w $brightness > /dev/null 2>&1
		if [[ "$change" = true ]]; then
			echo "$brightness"
		fi
	fi
fi
